### ISSUE TITLE
Don't use 1st person in README

### ISSUE THREAD

**Issue by malmans2** [MillionConcepts/lhorizon#10]
There are two authors on the paper and it looks like there are two maintainers.
In the README, I wouldn't use 1st person (e.g., "I wrote"). Either use "we" or the github handle if you prefer to be more specific.

https://github.com/openjournals/joss-reviews/issues/3495https://github.com/openjournals/joss-reviews/issues/3495

**Comment by m-stclair** [comment]
addressed in https://github.com/MillionConcepts/lhorizon/commit/9acc043374f0f81889f4f02e0a4e4db082dc0f03
