### ISSUE TITLE
OBSERVER table quantity codes

### ISSUE THREAD

**Issue by malmans2** [MillionConcepts/lhorizon#15]
I'm wondering if it's worth adding a function/method to retrieve the footnote at the end of [this notebook](https://github.com/MillionConcepts/lhorizon/blob/main/lhorizon/examples/mars_sun_angle.ipynb)? 

https://github.com/openjournals/joss-reviews/issues/3495

**Comment by m-stclair** [comment]
I would _like_ to do this. Unfortunately, as far as I can tell, there is no way to retrieve this concise table of quantity codes from the query interface. I can retrieve a formal prose description of every quantity value, but this is about 20 pages long and would not serve the same purpose. I _think_ the best I could do is add a reference to the section of the web documentation this table is taken from. (I suppose I could also scrape the text from the web documentation, but this does not seem very useful or guaranteed to be stable.)

**Comment by m-stclair** [comment]
oh, or are you perhaps suggesting that I just squirrel it away as a string literal somewhere in the module and add a function/method to retrieve it?

**Comment by malmans2** [comment]
> oh, or are you perhaps suggesting that I just squirrel it away as a string literal somewhere in the module and add a function/method to retrieve it?

If there's no easy way to retrieve it from the description, yes I think it would work as long as the table is not going to change. Otherwise, maybe just a clear link in the documentation to the long description would be helpful. I'll leave it up to you.

**Comment by m-stclair** [comment]
the situation is actually somewhat worse than I thought. the table provided in the documentation is explicitly noted as subject to change at any time and is already out of date, meaning that the only way to access an up-to-date table of quantity codes is via telnet or the interactive web CGI (which is different from the batch CGI used by lhorizon and would require spoofing browser interaction to access programmatically)...I thought a little more about the problem and found a way to trick the telnet endpoint into printing the table. this is probably a little fragile, but better than forcing users to perform multiple interaction steps on external resources to have a correct list of options. see https://github.com/MillionConcepts/lhorizon/commit/166f7291ef9b09c14bebc9b396087a8d0be6d7a6
