### ISSUE TITLE
Publish to PyPI and/or conda-forge?

### ISSUE THREAD

**Issue by malmans2** [MillionConcepts/lhorizon#17]
You could publish the package on PyPI and conda-forge.
It's quite easy to set up a GH workflow that will publish every time a new tag is created.

The basic workflow is described [here](https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/), but there are many tutorials online.

https://github.com/openjournals/joss-reviews/issues/3495

**Comment by m-stclair** [comment]
I have added actions for publishing to TestPyPi and PyPi, and `lhorizon` is [now available on PyPi](https://pypi.org/project/lhorizon/). 

I have also created a `conda-forge` recipe for `lhorizon` and [submitted a PR to staged-recipes](https://github.com/conda-forge/staged-recipes/pull/15898). Leaving this issue open pending resolution of that PR.

**Comment by malmans2** [comment]
Nice! 
I think it's now better to suggest `pip/conda install lhorizon` in the installation section.

I would probably do something consistent for binder as well.
E.g., replace
https://github.com/MillionConcepts/lhorizon/blob/a25f71435ea8b9b5de5942c735163789cd7eaadb/.binder/postBuild#L3
with
`conda install -c conda-forge pip # or just add pip to environment.yml` 
`pip install -e .`

**Comment by m-stclair** [comment]
I’ve made install docs consistent and updated binder, and the package is up on c-f! https://anaconda.org/conda-forge/lhorizon
