### ISSUE TITLE
Paper review

### ISSUE THREAD

**Issue by malmans2** [MillionConcepts/lhorizon#18]
I have a couple o minor comments regarding the paper:

- [x] Line 9: I would mention/cite the other interfaces available (if these are the packages mentioned in "Other Related Work", I'd make it more obvious)
- [x] Line 13: Cite [numpy](https://numpy.org/citing-numpy/) and [pandas](https://pandas.pydata.org/about/citing.html)
- [x] Line 100: The doi/link to Annex 2020 is broken
- [x] Line 107: There's no link/doi to Giorgini 2015. See: https://ui.adsabs.harvard.edu/abs/2015IAUGA..2256293G/exportcitation

https://github.com/openjournals/joss-reviews/issues/3495

**Comment by m-stclair** [comment]
thanks for finding these; let me know if I've adequately addressed them.

**Comment by malmans2** [comment]
> thanks for finding these; let me know if I've adequately addressed them.

Yes, thanks!
