### ISSUE TITLE
requirements.txt for pipenv

### ISSUE THREAD

**Issue by steo85it** [MillionConcepts/lhorizon#22]
Maybe add a `requirements.txt` list of dependencies (translation of `environment.yml`) for manual installations of cloned code to pipenv (for those who don't use conda envs)

**Comment by m-stclair** [comment]
Sure, no problem. The added file contains all dependencies listed as required and optional in `setup.py`, including for benchmarks: https://github.com/MillionConcepts/lhorizon/commit/20c380adcb2ef124aab2da87ffb6910c121f1e77
