### ISSUE TITLE
do tests verify results against external sources (e.g., an Horizons dump)?

### ISSUE THREAD

**Issue by steo85it** [MillionConcepts/lhorizon#24]
As from the title, are the (very extensive and working well) tests provided with the code only checking internal functionalities and consistency, or are they also verifying that results by the package are consistent with output by the `Horizons` platform (or by `spiceypy` or `astropy` or whatever else)?

If yes, I would suggest to:
- [x] add some brief description to routines and functions in `lhorizon/tests`, as that's completely missing at present

If not, then:
- [ ] please add one or more tests comparing your results for a particular application (some vector/range computation between features/bodies) to equivalent information retrieved from other sources (a dump of Horizons output to csv, a spiceypy/astropy call).

https://github.com/openjournals/joss-reviews/issues/3495

**Comment by m-stclair** [comment]
Many of the tests check against saved csv dumps of output from `Horizons`. However, of course, all of the _inputs_ to the package are also basically live dumps of similar output from `Horizons`, so this is less reassuring than it could be. To guard against the possibility that either the tests or the package as a whole are  parsing `Horizons` output in a pervasively but subtly poor way that is introducing a systematic numerical error, I also have a few black-box "reasonableness" checks, e.g.:

- is the angular diameter of the Moon considerably greater or smaller than I think it should be relative to an Earth observer?
- Are rays drawn from a point on Mars to a point on the Moon, and then back from that point on the Moon to the same point on Mars, reflections of one another to within a small margin of error?
   
Do you think I should have more of these?  I have certainly considered adding calls to other data sources. Other purely analytical tests could be added, like checking to see if the position `lhorizon` reports for a particular planet is within the expected margin of error from  its approximate position as computed using Keplerian formulae.

In either case, I can add more documentation to `lhorizon.tests`.

**Comment by m-stclair** [comment]
added some explanatory docstrings and comments to `lhorizon.tests` submodules: 30a9140

leaving this issue open to get your opinion on the broader verification question.

**Comment by steo85it** [comment]
Thanks for the detailed explanation: I think the tests are more than adequate and that should now be clear from the docstrings.
