### ISSUE TITLE
Javascript interfaces for NASA Horizons

### ISSUE THREAD

**Issue by jumpjack** [MillionConcepts/lhorizon#28]
This is not an issue, but given that discussions are not enabled, this is the only place where I can post this info...

For those interested, I am working to two graphical interfaces to NASA Horizons:

 - [NHUGUI - NASA Horizons (unofficial) GUI](http://win98.altervista.org/space/exploration/NHUGUI.html)
 - [Space explorer tracker](http://win98.altervista.org/space/exploration/3d/space-explorer-tracker.html?orbiter=-168&body=@499&start=2021-FEB-10%2020:40&stop=2021-FEB-18%2020:46&step=10m&3dzoom=10000&radius=33922)  (use http, not https)

The second page is  quite buggy and poorly documented.... but once you figure out how to use it, it gives nice results:

![image](https://user-images.githubusercontent.com/1620953/156404414-ba7f5d4c-20a8-4c1e-8c0f-d8b7b0b59374.png)

I didn't upload the source code anywhere, but it's just plain HTML+javascript without obfuscation, so it's just a matter to saving the pages locally.

**Comment by cmillion** [comment]
Thank you. I appreciate the effort, but I think this isn't a good forum for this information. Maybe the OpenPlanetary forum or an `astropy` forum or mailing list. Good luck and godspeed.

**Comment by jumpjack** [comment]
I recently discovered that github has embedded (but hidden) support for discussion forums in repository settings :-)
![image](https://user-images.githubusercontent.com/1620953/156768017-08706728-0ca4-42ad-a566-a0b0a035c175.png)

Thanks anyway for the hint on OpenPlanetary.
