### ISSUE TITLE
Test failure

### ISSUE THREAD

**Issue by malmans2** [MillionConcepts/lhorizon#4]
Hi there,

I've run the tests and I'm getting one failure. I'm using this [environment](https://github.com/MillionConcepts/lhorizon/blob/main/environment.yml).
Here is the log: [pytest.log](https://github.com/MillionConcepts/lhorizon/files/6830705/pytest.log)

On a slightly different note: Have you considered a [github CI workflow](https://docs.github.com/en/actions/guides/building-and-testing-python)?
I've set it up for a few python projects, so I'd be happy to send a PR if that works for you.

https://github.com/openjournals/joss-reviews/issues/3495

**Comment by m-stclair** [comment]
Sorry, I wasn't getting notifications from this thread.

Test is not taking the value modulo 360! Thank you, I'll fix that. 

I have considered it but have never used one. If you'd like to send a PR, that would be great.

**Comment by m-stclair** [comment]
should be fixed by https://github.com/MillionConcepts/lhorizon/commit/c86f83826710efc0bd927c82b6e9e260dda5305c.
